# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:18-alpine AS builder

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json /app/

# Install app dependencies
RUN npm install --ignore-scripts

# Bundle app source
COPY . .

# Build the server
RUN npm run build

# Only keep the necessary build files and node_modules
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy built files from the builder
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json
COPY --from=builder /app/node_modules /app/node_modules

# Define the command to run the app
ENTRYPOINT ["node", "build/index.js"]
